### ISSUE TITLE
Day 2 – Creating a basic WordPress theme.

### ISSUE THREAD

**Issue by pokhiii** [ColoredCow/wordpress-bootcamp-2020#2]
We’ll create a simple WordPress theme using Bootstrap4 and will see how WordPress does the magic with just a couple of files.

### To-Dos

- [ ] Start writing your own WordPress theme. [What is a Theme?](https://developer.wordpress.org/themes/getting-started/what-is-a-theme/)
- [ ] Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

### Links

1. [Template Hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/)
1. [Bootstrap](https://getbootstrap.com/)

**Comment by pokhiii** [comment]
Download sublime text here: https://www.sublimetext.com/3

**Comment by Sam23599** [comment]
Start writing your own WordPress theme. What is a Theme?
 Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by Riya2903** [comment]
- [x] Start writing your own WordPress theme. What is a Theme?

 

- [x] Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by Sam23599** [comment]
Download WordPress core - Get WordPress
 Create a database for your WordPress site
 Setup virtual host for your site
 After setting up virtual host, visit your site in a browser
 WP Configuration 1 - Create database connection
 WP Configuration 2 - Provide site and admin account details

**Comment by Sam23599** [comment]
Start writing your own WordPress theme. What is a Theme?
 Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

- [ ]

**Comment by junaid1010** [comment]
- [x] Start writing your own WordPress theme. What is a Theme?

- [x]  Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by Sam23599** [comment]
- [x]  Start writing your own WordPress theme. What is a Theme?

- [x]  Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by swati999-bhatt** [comment]
- [x] Start writing your own WordPress theme. What is a Theme?

- [x]  Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by gangwar4adarsh** [comment]
- [x] Start writing your own WordPress theme. What is a Theme?

 

- [x] Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by gaurish-saini** [comment]
- [x] Start writing your own WordPress theme. What is a Theme?
- [x]  Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.

**Comment by gaurish-saini** [comment]
- [ ] Start writing your own WordPress theme. What is a Theme?
- [ ]  Using a Bootstrap, put some elements of Bootstrap on your page like Carousel, form, etc.
